AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for global hosting
Parameters:
  S3BucketName:
    Type: String
    Description: Name of the global S3 bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
        -
          Action:
            - s3:GetObject
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
          Principal: "*"
Outputs:
  S3BucketName:
    Description:  Name of the global S3 bucket
    Value: !Ref S3Bucket
